### ISSUE TITLE
Release 2.83.10+rev2

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-rockpi#15]
This issue is to track the release of a balenaOS build from 2.83.10+rev2 for the rockpi DT

**Comment by 20k-ultra** [comment]
I saw @joehounsham request that we do not release this yet due to some commercial details so follow up with him before doing this perhaps. See jf ticket.

**Comment by shawaj** [comment]
> I saw @joehounsham request that we do not release this yet due to some commercial details so follow up with him before doing this perhaps. See jf ticket.

@joehounsham can we get this merged ASAP now?

As it's blocking our production from proceeding

Cc @marvinarnold @vpetersson

**Comment by floion** [comment]
@shawaj was this release needed for the SPI functionality?

**Comment by floion** [comment]
Since the SPI fix is in version `v2021.10.3` I will close this bug report
