### ISSUE TITLE
Non flasher image

### ISSUE THREAD

**Issue by shawaj** [balena-os/balena-rockpi#25]
It is possible to [directly flash the eMMC of the RockPi](https://wiki.radxa.com/Rockpi4/install/eMMC), or you can [flash it over USB](https://wiki.radxa.com/Rockpi4/dev/usb-install), or on units without eMMC to use an SD card as the boot device.

In both cases, it is necessary to have a non-flasher image

Is it possible for balena to support both image types for the same device? Or have a flasher and non-flasher version of the device?

**Comment by floion** [comment]
There are some plans to offer both at some point, but not currently. A workaround for now would be that one could extract the non-flasher image from the dashboard image and use that.
Are you interested in that for mass provisioning purposes?

**Comment by shawaj** [comment]
@floion yes that would be useful. we are currently using the balena-cli to download the base os, configure it and preload it.

Is it possible to then take that image and unwrap the bit we can just program directly onto the eMMC?

Thanks

**Comment by shawaj** [comment]
Closing as this worked ok https://github.com/balena-os/balena-image-flasher-unwrap
