### ISSUE TITLE
Investigate disabling wifi / bt power management

### ISSUE THREAD

**Issue by floion** [balena-os/balena-rockpi#49]

**Comment by shawaj** [comment]
@MuratUrsavas could you comment on this on the ticket?

**Comment by MuratUrsavas** [comment]
From the latest tests I've done about power saving, I guess it is off by default in newer drivers. But I'm not sure of course. Maybe the default Debian Radxa image had it disabled and driver update didn't change it.

What I know is, having power save enabled, the latency increases a lot. So it is best to keep it off.

**Comment by shawaj** [comment]
@MuratUrsavas do you know the process for turning it off?

**Comment by floion** [comment]
Checked on the image from PR https://github.com/balena-os/balena-rockpi/pull/56 and power saving is off by default:

```
root@ff37d9c:~# iw wlan0 get power_save
Power save: off
```

**Comment by floion** [comment]
Checked the brcmfmac source code and it seems off by default: https://github.com/balena-os/cypress-backports/blob/v5.4.18-2021_0527/v5.4.18-backports/net/wireless/core.c#L1389

Anyway, will also disable from Kconfig just to be sure that future changes to core.c won't take us by surprise: https://github.com/balena-os/balena-rockpi/pull/58

**Comment by shawaj** [comment]
Thanks @floion :-)

Let us know when there's an OS update available

**Comment by floion** [comment]
This is now in OS release `v2022.1.3` which is available in production
