### ISSUE TITLE
RockPi4 request for non ESR and ESR 2022.04

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-rockpi#93]
1) The latest WiFi and Bluetooth patches, done on ESR version, are missing.
2) The SPI device has to wrong name (devspi1.0) but our software expects devspi32766.0 as on the ESR release.
3) Disable serial console on UART2 and enable it as userspace device.

These are requested for both master and the next ESR branch

**Comment by acostach** [comment]
```
timeout 10
menu title select kernel
```
above kernel should be removed from /mnt/boot/extlinux/extlinux.conf for the next release according to the attached JF ticket. The meta-balena PR that has already been merged and included in the NON-ESR release should have fixed the boot problem already, as it has been confirmed by the customer.

**Comment by acostach** [comment]
Customer does not have a free RockPi4B with eMMC release right now to test the latest production non-ESR release, we will perform testing on our side for the next ESR and non ESR releases to validate the 3 items in the description.

**Comment by rahul-thakoor** [comment]
@acostach make sure to use 9600 baud when testing uart2 as suggested by customer

> For reproduction of the issue, please make sure you're using 9600 baud. Looks like faster speeds may decrease chance of a reproduction.

**Comment by acostach** [comment]
Thanks for adding the note @rahul-thakoor . U-boot should print no output and ignore all input on UART2, so the baud rate should have no influence over this but we'll test this.

**Comment by floion** [comment]
Released the ESR version v2022.4.1
